//tealium universal tag - utag.565 ut4.0.201709132214, Copyright 2017 Tealium.com Inc. All Rights Reserved.
var $CVO=window.$CVO||[];try{(function(id,loader,u){try{u=utag.o[loader].sender[id]={}}catch(e){u=utag.sender[id]};u.ev={'view':1,'link':1};u.attr={};u.clientid='godaddy';u.event_type="";u.event_id="";u.event_value="";u.base_url='//d1ivexoxmp59q7.cloudfront.net/'+u.clientid+'/live.js';u.map={"cvo_event":"event_type","dom.referrer":"domain","shopper_id":"id","cvo_val":"event_value"};u.extend=[function(a,b){try{if((b['app_name'].toString().toLowerCase()=='wsb'.toLowerCase()&&typeof b['qp.orderId']!='undefined'&&b['qp.orderId']!='')||(b['app_name'].toString().toLowerCase()=='nemo'.toLowerCase()&&b['base_pathname'].toString().toLowerCase().indexOf('onboarding'.toLowerCase())>-1)||(b['app_name']=='onboarding'&&typeof b['qp.orderId']!='undefined'&&b['qp.orderId']!='')){b['cvo_val']='1'}}catch(e){utag.DB(e)}},function(a,b){try{if((b['app_name'].toString().toLowerCase()=='nemo'.toLowerCase()&&b['base_pathname'].toString().toLowerCase().indexOf('onboarding'.toLowerCase())>-1)){b['cvo_event']='trial.ols'}}catch(e){utag.DB(e)}},function(a,b){try{if((b['app_name'].toString().toLowerCase()=='nemo'.toLowerCase()&&b['base_pathname'].toString().toLowerCase()=='/admin/onboarding'.toLowerCase())){b['_corder']=b['cp.ols_oid']}}catch(e){utag.DB(e)}},function(a,b){if((typeof b.page_type!=undefined&&b.page_type=='orderconfirmation')||b['dom.domain'].toString().indexOf('dcc.godaddy.com')>-1||(typeof b._pathname1!='undefined'&&(b._pathname1.toString().indexOf("domains")>-1||b._pathname1.toString().indexOf("tlds")>-1)))
{utag.ut.loader({id:"tealium_mm_uuid",type:"img",src:"//bs.serving-sys.com/serving?cn=um&dpid=38&rtu=$$https://collect.tealiumiq.com/vdata/i.gif?sizmek_id=[%tp_SyncUserID%]&tealium_vid="+utag.data['cp.utag_main_v_id']+"&tealium_account="+utag.data['ut.account']+"&tealium_profile=main$$"});}}];u.send=function(a,b,c,d,e,f){if(u.ev[a]||typeof u.ev.all!='undefined'){for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(typeof b[d]!=="undefined"&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(e[f]=="event_type"||e[f]=="event_id"||e[f]=="event_value"){u[e[f]]=b[d];}else{u.attr[e[f]]=b[d];}}}}
if(u.event_id==""){u.event_id=b.order_id||b._corder};if(u.event_value==""){u.event_value=b._csubtotal};if(u.event_type==""){u.event_type=b._ctype};if(b['dom.domain'].toString().indexOf("onboarding.godaddy.com")>-1&&b['dom.referrer'].toString().indexOf('cart.godaddy.com')===-1&&typeof b.order_id!=="undefined"){u.event_type="trial.wsb";}
var shopper_id=u.attr.id||b._ccustid;if(shopper_id.indexOf('{{')==-1){if((u.attr.id||b._ccustid)&&b.event_type!='webpro'){u.attr.id=(u.attr.id?u.attr.id:b._ccustid);u.attr.city=(u.attr.city?u.attr.city:b._ccity);u.attr.state=(u.attr.state?u.attr.state:b._cstate);u.attr.zip=(u.attr.zip?u.attr.zip:b._czip);u.attr.country=(u.attr.country?u.attr.country:b._ccountry);$CVO.push(['trackUser',u.attr]);}}
var t=u.event_type.split(',');if(u.event_value!==1){var v=u.event_value.split(',');}
if(u.event_id==null||u.event_type=='webpro'){$CVO.push(['trackEvent',{type:u.event_type,id:u.event_id,amount:u.event_value}]);}else if(u.event_id&&u.event_type!=='webpro'){for(d=0;d<t.length;d++){var value=((typeof v[d]!="undefined")?v[d]:u.event_value);$CVO.push(['trackEvent',{type:((t[d])?t[d]:"sale"),id:u.event_id,amount:((value)?value:'0')}]);}}else if(u.event_type&&b.event_type!='webpro'){for(d=0;d<t.length;d++){$CVO.push(['trackEvent',{type:t[d]}]);}}
u.s=document.getElementsByTagName("script")[0];u.scr=document.createElement("script");u.scr.type="text/javascript";u.scr.src=u.base_url;u.s.parentNode.insertBefore(u.scr,u.s);}}
try{utag.o[loader].loader.LOAD(id)}catch(e){utag.loader.LOAD(id)}})('565','godaddy.godaddy');}catch(e){}
